### PR TITLE
Support guild vanity URLs

### PR DESCRIPTION
**Pull request by jchristgit**

### CODE REVIEW

**Comment by jchristgit** [comment]
### As a...

nostrum user

### I want to...

view Guild Vanity URLs

### such that...

99% of my cached guilds can grow in size for a field they will never have

**Review by Kraigie — APPROVED** [review]
BRAVO! jchristgit, you've really outdone yourself this time!

**Comment by jchristgit** [comment]
THANK YOU! Kraigie, I am forever thankful for the review.

**Comment by jchristgit** [comment]
Thanks!

**Pull request merged**
