### PR TITLE
Guns up

### PR DESCRIPTION
**Pull request by BrandtHill**
Make gun always retry shard and voice connections

### CODE REVIEW

**Comment by queer** [comment]
:gun: pew pew

**Review by jchristgit — CHANGES_REQUESTED** [review]
Very interesting.

But isn't this against OTPs design principles? Wouldn't this hang the nostrum application forever if we don't manage to start the shard session?

**Comment by BrandtHill** [comment]
The shard session genserver will already retry to establish a connection forever.
Currently, the shard's `gun` process will stop trying to reconnect if connectivity is lost long enough for `gun`'s default of `5` retries to be expended. In this case, every part of Nostrum will stay alive, including the shard session genserver, but no events will be received on that shard as the websocket connection is dead (I should think this is not intended behavior).

@Kraigie found [this snippet for genserver gun usage](https://github.com/GenericJam/websocket-client/blob/master/lib/websocket_client/websocket_client.ex#L176) which may work for auto reconnects (what happens to the original supervised gun process when we call `ws_upgrade` at the `gun_down` event? idk). This is really a bugfix more than an enhancement.

**Review by jchristgit — APPROVED** [review]
I see. Thank you for the explanation

**Comment by Kraigie** [comment]
Thanks!

**Pull request merged**
