### PR TITLE
Decode Member from modify_guild_member endpoint response

### PR DESCRIPTION
**Pull request by PixeLInc**

### CODE REVIEW

**Comment by Th3-M4jor** [comment]
Mostly a nitpick, but can you also modify the return value for the example in the doc comments to go with this fix?

**Review by jb3 — COMMENTED** [review]
Looks good to me!

**Review by jb3 — APPROVED** [review]
Why did they make the "comment" button green and the approve button grey?

**Comment by jb3** [comment]
Thanks!

**Pull request merged**
