### PR TITLE
Added constants for Discords arbitrary numbers

### PR DESCRIPTION
**Pull request by jirkavrba**

### CODE REVIEW

**Review by jchristgit — CHANGES_REQUESTED** [review]
I forgot to hit submit on my review....

Thank you for the PR! I have some smaller style comments, but apart from that it looks good.

**Review by jchristgit — APPROVED** [review]
Thank you!

**Comment by jirkavrba** [comment]
I've added links to the official Discord documentation in moduledocs to fix credo linting readability issues

**Review by jchristgit — APPROVED** [review]
Thank you!

**Comment by jchristgit** [comment]
Can you run `mix format` over your files, then we should be ready to go :slightly_smiling_face:

**Comment by jirkavrba** [comment]
Sorry I missed your comment from Sunday, I ran the command and pushed generated diff.

**Comment by jchristgit** [comment]
Thank you!

**Pull request merged**
