### PR TITLE
Revert to normalizing gateway keys to atoms.

### LINKED ISSUE #290: Key Error on GUILD_UPDATE
This is another case of Discord being inconsistent in using strings or atoms as keys when using ETF payloads.

If this happens more than once in a quick enough succession, the cache process is not restarted and events stop being sent to the user's Consumer process.

This currently happens on the latest commit to `master`.

```
[error] GenServer Nostrum.Shard.Stage.Cache terminating
** (KeyError) key :id not found in: %{"id" => [guild_id], "verification_level" => 1, "preferred_locale" => "en-US", "afk_channel_id" => nil, "vanity_url_code" => nil, [ . . . ]}
```

Stacktrace:
```
(nostrum 0.4.7) lib/nostrum/cache/guild_cache.ex:204: Nostrum.Cache.GuildCache.update/1
(nostrum 0.4.7) lib/nostrum/shard/dispatch.ex:151: Nostrum.Shard.Dispatch.handle_event/3
(nostrum 0.4.7) lib/nostrum/shard/dispatch.ex:42: Nostrum.Shard.Dispatch.handle/1
(elixir 1.12.0) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
(nostrum 0.4.7) lib/nostrum/shard/stage/cache.ex:23: Nostrum.Shard.Stage.Cache.handle_events/3
(gen_stage 1.1.0) lib/gen_stage.ex:2462: GenStage.consumer_dispatch/6
(gen_stage 1.1.0) lib/gen_stage.ex:2641: GenStage.take_pc_events/3
(stdlib 3.15.2) gen_server.erl:695: :gen_server.try_dispatch/4
```

### PR DESCRIPTION
**Pull request by jchristgit**
By the past bug reports and various issues related to variation of key
types coming from the gateway, this has become more of a hassle than
not.

This commit goes back to the behaviour of normalizing all keys to atoms,
with the small exception that snowflakes which look like integers are
parsed as integers. This was based off Matt Nowack (@ihumanable)s work
in our Discord channel, with a small documentation addition. Thank you!

Struct fields getters are updated to `.key` or `[:key]` depending on
whether or not they are documented as optional in the Discord API
documentation, with the exception of the `PartialApplication.flags`
field, which I blandly assume to be present.

Fixes #290.
Supersedes #291.
Supersedes #299.

### CODE REVIEW

**Comment by Th3-M4jor** [comment]
Unless you already account for it elsewhere, and/or I missed it, It's possible that they key passed to `maybe_to_atom` will already be an integer. The API docs say that for ETF payloads all snowflakes will be 64-bit integers.
https://discord.com/developers/docs/topics/gateway#etfjson

**Comment by jchristgit** [comment]
Hmm, I'm not sure if we had that case then. In that case, was #252 a bug on Discord's side? Or wrong documentation? Was this all wrong? 🤨

**Comment by Th3-M4jor** [comment]
I'm not sure if that was a bug on discord's end or not, but I myself have checked the payload received on interactions and when keys were snowflakes they were sent as integers.

So I guess we should handle both for now? But make string snowflake keys be a warning since that should be a bug on discord's end according to the API docs.

**Comment by jchristgit** [comment]
>  I'm not sure if that was a bug on discord's end or not, but I myself have checked the payload received on interactions and when keys were snowflakes they were sent as integers.

Huh - I observed the opposite, keys sent as binaries, which is why that issue was opened in the first place. Perhaps another case of inconsistent key types?

> So I guess we should handle both for now? But make string snowflake keys be a warning since that should be a bug on discord's end according to the API docs.

I'm 50/50 on adding a warning. On one hand, it's wrong according to the documentation, on the other hand, for someone who's building a bot a log message like that is noise and not really useful, isi t?

**Review by jb3 — APPROVED** [review]
Lovely, lovely.

**Comment by jchristgit** [comment]
Thank you, thank you, Joe. Very kind of you.

**Review by Kraigie — APPROVED** [review]
Everything here looks good to me! I don't have strong opinions on adding a warning like was discussed.

Can't wait to revert this again in a week! :shipit: 🦖

**Comment by jchristgit** [comment]
Thank you, thank you, Craig. Very kind of you.

**Comment by jchristgit** [comment]
Thanks!

**Pull request merged**
