### PR TITLE
Fix error on README.md example.

### PR DESCRIPTION
**Pull request by DarkCode01**
Update example on README.md.

Issue Closed: #167

### CODE REVIEW

**Comment by DarkCode01** [comment]
Updated folder `examples` and create a simple project using cache and event consumer on project example.

**Review by jb3 — CHANGES_REQUESTED** [review]
This feels like it could be a good improvement, but the logic is in the wrong place right now.

The `command`, `get_cached_with_fallback` and so on should all be inside the cached consumer, holding them at the root application level is bad practice and makes things hard to find.

Let's have a fully self-contained consumer without using the cache in `examples/event_consumer/lib/event_consumer/basic_consumer.ex` and one in `examples/event_consumer/lib/event_consumer/cache_consumer.ex` using the cache functions you've written.

We should also use better naming, let's switch to `EventConsumer.BasicConsumer` and `EventConsumer.CacheConsumer`. We can then move the application logic into `EventConsumer` instead of `EventConsumer.Application`, removing a file and making things simpler. In my eyes we should have 3 files:
- Root application 
- Cache consumer
- Basic consumer

I've also left a few minnor comments where I think improvements could be made.

**Comment by jchristgit** [comment]
Hi @DarkCode01, are you still interested in working on this issue?

**Comment by jchristgit** [comment]
Thank you for the PR! As we have closed the initial issue and there was no more activity here, I am closing this PR. Feel free to open an issue if you feel like we are missing something!

**Pull request closed without merging**
