### PR TITLE
Allow for uploading files in interaction responses

### PR DESCRIPTION
**Pull request by Th3-M4jor**
Adds the option to include files when creating interaction responses. As an added bonus, the file's body can be an iolist and work just fine.

### CODE REVIEW

**Review by jb3 — APPROVED** [review]
All the changes look good. It might be nice to provide `file` as a backwards compatible option, thoughts @jchristgit?

**Comment by Th3-M4jor** [comment]
Yeah I might as well add that, in addition to a check for when both `:file` and `:files` are included

**Comment by Th3-M4jor** [comment]
Actually, we do provide `:file` as a backwards compatible option for both `execute_webhook` and `create_interaction_response`. It's just not documented because it should be treated as "soft deprecated" in my opinion.

**Review by jchristgit — APPROVED** [review]
Absolutely rock solid. Thanks!

**Comment by jchristgit** [comment]
Thanks!

**Pull request merged**
