### PR TITLE
Update `:kcl` from 1.3.0 to 1.4.0.

### PR DESCRIPTION
**Pull request by jchristgit**

### CODE REVIEW

**Review by Kraigie — APPROVED** [review]
Yep

**Comment by jchristgit** [comment]
Lockfiles are great! I love lockfiles. I have done nothing but read lockfiles
for the past three days. It's just so fun to browse "source" "code" that is not
wrapped at 80 lines! Did you know that my "Update ex_doc" PR actually updated
_everything but ex_doc_? Right, me neither. I love lockfiles. Lockfiles are
great! This PR in turn actually updates ex_doc, but `kcl` in `mix.lock` is
already updated to `1.4.0`, whilst `ex_doc` in `mix.lock` gets updated to
`0.25` despite it being on `0.24` beforehand, which is **also specified in
`mix.exs`**. I love lockfiles! Lockfiles are great! I'm not sure if I was in a
vegetative state of mind whilst making the update PRs, but I can convince you
that I can write Elixir code blind. I just cannot read lockfiles blindly. That
is not to say that lockfiles are bad. Lockfiles are great! I love lockfiles!

**Comment by jchristgit** [comment]
Thanks!

**Comment by jerbob** [comment]
thanks

**Pull request merged**
