### PR TITLE
add messages field to application data resolved

### PR DESCRIPTION
**Pull request by Th3-M4jor**
This allows Nostrum to support context menu commands on messages.

tested it on my bot to confirm that it works.

### CODE REVIEW

**Comment by jchristgit** [comment]
Thanks!

This looks good from a code perspective. When does Discord send us the message objects in the interaction? I retrieve
```elixir
      messages: nil,
```
when testing this locally.

**Comment by khionu** [comment]
Only with Message/User Commands

**Comment by jchristgit** [comment]
Thanks for the clarification. I'll gobble this in since it seems straightforward enough.

**Review by jchristgit — APPROVED** [review]
Thanks!

**Comment by jchristgit** [comment]
Thanks!

**Pull request merged**
