### PR TITLE
Fix dialyzer complaints on master.

### PR DESCRIPTION
**Pull request by jchristgit**
Two missing warnings are not fixed as part of this PR, there's missing
struct definitions for the user connection and guild integration type.

### CODE REVIEW

**Comment by jchristgit** [comment]
@BrandtHill could you take a look over the voice changes & whether that looks proper?

```elixir
lib/nostrum/voice/audio.ex:136:pattern_match
The pattern can never match the type.

Pattern:
{:error, _reason}

Type:
%Porcelain.Process{:err => _, :out => _, :pid => _}

________________________________________________________________________________
lib/nostrum/voice/audio.ex:177:pattern_match
The pattern can never match the type.

Pattern:
{:error, _reason}

Type:
%Porcelain.Process{:err => _, :out => _, :pid => _}
```

was the Dialyzer error reported there

**Comment by BrandtHill** [comment]
> @BrandtHill could you take a look over the voice changes & whether that looks proper?
> 
> ```elixir
> lib/nostrum/voice/audio.ex:136:pattern_match
> The pattern can never match the type.
> 
> Pattern:
> {:error, _reason}
> 
> Type:
> %Porcelain.Process{:err => _, :out => _, :pid => _}
> 
> ________________________________________________________________________________
> lib/nostrum/voice/audio.ex:177:pattern_match
> The pattern can never match the type.
> 
> Pattern:
> {:error, _reason}
> 
> Type:
> %Porcelain.Process{:err => _, :out => _, :pid => _}
> ```
> 
> was the Dialyzer error reported there

This comes from incomplete type specs for the Porcelain functions. Check [this PR](https://github.com/alco/porcelain/pull/54) for the fix to that library. 
Maybe this can be changed to have a catch block since a new Porcelain release is unlikely? I will take a look.

**Review by BrandtHill — CHANGES_REQUESTED** [review]
How I have it here is correct since `Porcelain.spawn` can return an error tuple. I've just created PR #277 to instruct dialyzer to ignore the warnings since the error is due to improper type specs. from the lib.

**Comment by jchristgit** [comment]
Yes, you're correct. I will kill them.

**Comment by jchristgit** [comment]
Killed. Thanks, @BrandtHill.

**Comment by jchristgit** [comment]
Merging as this is hen's critter.

**Comment by jchristgit** [comment]
Thanks!

**Pull request merged**
