### PR TITLE
Fix Members not updating new `nil` fields in cache

### PR DESCRIPTION
**Pull request by skippi**
This fixes the #91 issue.

I've also included some extra cleanups while I was here.

### CODE REVIEW

**Comment by Kraigie** [comment]
Gonna' put this on hold, pending design decisions from #98

**Comment by skippi** [comment]
I think we should focus on the design decisions here, since this is a more immediate issue. With that being said, I think 43f2b1d covers most of the concerns you might've had with this PR. Check it again when you get the chance. I've included a use module for the struct construction logic.

**Comment by Kraigie** [comment]
I'm super hesitant to include the changes in this PR as they really fall out of line with the issue at hand. I think we should just solve this issue first and worry about integrating those changes properly elsewhere. 

Let me know your thoughts.

**Comment by skippi** [comment]
This is ready for code review.

**Comment by Kraigie** [comment]
Thanks!

**Pull request merged**
